import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingprogrammer blog, hunting blog"
        />
      </Head>
      <main className={styles.main}>
        <div className={styles.imgWrapper}>
          {/* <Image src='/homeimg.jpg' alt="home-img" className={styles.myImg} width={672} height={448} /> */}
          <img
            src="/homeimg.jpg"
            alt="home-img"
            className={styles.myImg}
            width={372}
            height={300}
          />
        </div>
        <h1 className={styles.title}>
          <span>&lt;HuntingProgrammer /&gt;</span>
        </h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae,
              exercitationem.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae,
              exercitationem.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae,
              exercitationem.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
