import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
        <style jsx>
          {`
          h2{
            font-size: 35px;
          }
          h3{
            font-size: 25px;
          }
          `}
        </style>
      <Head>
        <title>Hunting Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingprogrammer blog, hunting blog"
        />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}><span>Hunting Programmer</span></h1>
        <div className={styles.imgWrapper}>
        {/* <Image src='/homeimg.jpg' alt="home-img" className={styles.myImg} width={672} height={448} /> */}
        <img src='/homeimg.jpg' alt="home-img" className={styles.myImg} width={672} height={448} />
        </div>
        <p className={styles.description}>
          A blog for hunting programmers by hunting programmer
        </p>

        <div>
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}
